AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  smd-pr-agent

  Sample SAM Template for smd-pr-agent

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    MemorySize: 512

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  PRAgentSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: smd-pr-agent-202411
      Description: Secret to store GITHUB_WEBHOOK_SECRET and OPENAI_KEY
      SecretString: !Sub |
        {
          "GITHUB__DEPLOYMENT_TYPE": "app",
          "GITHUB__WEBHOOK_SECRET": "dummy-key",
          "GITHUB__APP_ID": "dummy-key",
          "OPENAI__KEY": "dummy-key"
        }
      Tags:
        - Key: Purpose
          Value: Manage API Keys and Secrets
        - Key: Version
          Value: v202411
    UpdateReplacePolicy: Retain

  PRAgentFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Events:
        ProxyResource:
          Type: HttpApi
          Properties:
            PayloadFormatVersion: "2.0"
            Path: /{proxy+}
            Method: ANY
        RootResource:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
      Environment:
        Variables:
          OPENAI__KEY: "{{resolve:secretsmanager:smd-pr-agent-202411:SecretString:OPENAI__KEY}}"
          GITHUB__WEBHOOK_SECRET: "{{resolve:secretsmanager:smd-pr-agent-202411:SecretString:GITHUB__WEBHOOK_SECRET}}"
          GITHUB__DEPLOYMENT_TYPE: "{{resolve:secretsmanager:smd-pr-agent-202411:SecretString:GITHUB__DEPLOYMENT_TYPE}}"
          GITHUB__APP_ID: "{{resolve:secretsmanager:smd-pr-agent-202411:SecretString:GITHUB__APP_ID}}"
          AZURE_DEVOPS_CACHE_DIR: "/tmp"
    Metadata:
      DockerTag: latest
      DockerContext: .
      Dockerfile: docker/Dockerfile.lambda

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PRAgentApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${PRAgentFunction}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  PRAgentFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt PRAgentFunction.Arn
  PRAgentFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt PRAgentFunctionRole.Arn
