# QUICKSTART:
# Copy this file to .secrets.toml in the same folder.
# The minimum workable settings - set openai.key to your API key.
# Set github.deployment_type to "user" and github.user_token to your GitHub personal access token.
# This will allow you to run the CLI scripts in the scripts/ folder and the github_polling server.
#
# See README for details about GitHub App deployment.

[openai]
key = ""  # Acquire through https://platform.openai.com
#org = "<ORGANIZATION>"  # Optional, may be commented out.
# Uncomment the following for Azure OpenAI
#api_type = "azure"
#api_version = '2023-05-15'  # Check Azure documentation for the current API version
#api_base = ""  # The base URL for your Azure OpenAI resource. e.g. "https://<your resource name>.openai.azure.com"
#deployment_id = ""  # The deployment name you chose when you deployed the engine
#fallback_deployments = []  # For each fallback model specified in configuration.toml in the [config] section, specify the appropriate deployment_id

[pinecone]
api_key = "..."
environment = "gcp-starter"

[anthropic]
key = "" # Optional, uncomment if you want to use Anthropic. Acquire through https://www.anthropic.com/

[cohere]
key = "" # Optional, uncomment if you want to use Cohere. Acquire through https://dashboard.cohere.ai/

[replicate]
key = "" # Optional, uncomment if you want to use Replicate. Acquire through https://replicate.com/

[groq]
key = "" # Acquire through https://console.groq.com/keys

[huggingface]
key = "" # Optional, uncomment if you want to use Huggingface Inference API. Acquire through https://huggingface.co/docs/api-inference/quicktour
api_base = "" # the base url for your huggingface inference endpoint

[ollama]
api_base = "" # the base url for your local Llama 2, Code Llama, and other models inference endpoint. Acquire through https://ollama.ai/

[vertexai]
vertex_project = "" # the google cloud platform project name for your vertexai deployment
vertex_location = "" # the google cloud platform location for your vertexai deployment

[google_ai_studio]
gemini_api_key = "" # the google AI Studio API key

[github]
# ---- Set the following only for deployment type == "user"
user_token = ""  # A GitHub personal access token with 'repo' scope.
deployment_type = "user" #set to user by default

# ---- Set the following only for deployment type == "app", see README for details.
private_key = """\
-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAzlcliJ9nlH4c4vDgRcbyqUU9ebauDZoaiGxYzFIlf1ezfV3Z
ert65L2T79YbnjYhWcDLZQ5P0CEit+IPIqhfne9+LidjYu3V3VDD+fVCtfuhUDNo
NQok1+LN6YWuFXFiKf2P5gn3uPBY4tsENtk0S1dueyRHBVtvLGl6hK8Jq8juxVwU
Q/XwRyUWI1flk5kBoxM999UBaWyVKcX5g6ztxUhm+mH+L5vI4G9xOtQLOeNL2JJ1
iCyutFMoUrxSW52sqrlpq3CKuyHQIYiaioXrgf23nkw9yLhOceqf8RFkIrKcaIPT
EmA87hPj9+34zuE/cyAZt4s6IQFlKZTxlTVouQIDAQABAoIBAA+KcMFBgEOm2/Yb
vkiDG3O0S1UHdUSA/s6XmniJF1nn+RTQJLkhtbfUr3e44Iuh+BESfD84PLqoRD0l
QY6Sr+DtUMuZG9svnpP0qU4CMuwR76xiss6L3QqFgoy8DMiAqawP9O6WgZnkQE2V
wVOAOHgUNbYAnXjB0jW+HAQySsAtV1vaMWndPO3jmrmSnXNXQuKL/5v1qONLvZQ0
97ugNMLI04T0AIdSpx5sqsuIWZMVWGvhecthwXIOI/fBMskiTUj/gSaWnTMJSJFQ
b1cx0GTNB2yjr/MBqAz2WK+N84Vbq/cc69JBrZSDPsU4uHlJE25Da7CncNzPd3X4
hPOCJCECgYEA9arWo658y7eHAUkzedoPUB4vPUDqK4a92I+TV510xjb0moNpwMVO
Zhbr/KeFA5wzJeYga8sZn2C+2RVIabq7oAc6yUk5qw8U/9jXq1DRPMneB4v4tbIw
55kDqEbsP8tpcPhKNCybN91ZuNPe5UOZFMJoYTUu3IZbopJHiGalK4sCgYEA1wTd
iu2BFrTuitVNIfoFA5PipW+xvcVmFPsno/Fs1AD3xsVppCQEcUDPvFg6bypmHMFj
OMlWcKIE2lgnbvBIMw3g2VNKLZb34ZNStztOOIqeBDZDHLGfTtqlHlw2aKEui/fa
3mvqXseo/KWJmDYlEdR1pgq0P4KQywWrca+l1UsCgYA9/kBvyaZgWg3Ne0VsKGTY
2OUe1fTByxy5O3H5GBjRtCiBnUvgg2nHRV2DwlpEkPQvSiVATl5G48kFSuOdGqwi
M/DXvoy45/NqpLO33YsPhflrehzm7PJ+XxSXMF6JsrEG+wDurZr1u/vaMkz7GdXV
cUGZ1ivfJmCVY8h9WTmxBQKBgQCTb6ihvJ2JfmMbG4uaQp/xhhQhMGeGIrcOp/DU
f5UKAefkijUX8gKBzdkj4rOeykneadSpeZUmAlKljVDsxyIar+d/3Za9kAlEygor
ziSirJoRdUurfzgnj9Es8jn0oKEUJM4VOZYpi2qaYr/oeSgOA8rwIeLasaKrM6YN
fE2P5QKBgQCJPrRgMc3c5FeSvg1lLusOJ2Tnu0GJUDbR5TBVSO697XoxdzaY1dPJ
HCeS7fgrSPZmXx4gTEIkReRaz3gMhx8qBbefzWgX2BqvMsWFC2fsLZ0P4E0hnJd7
R30Bi26nHp7Uj9GLUAm6Olem1emHJGMTM2g0k9YAj4lo3ZkvY83O9g==
-----END RSA PRIVATE KEY-----
"""
app_id = 123456  # The GitHub App ID, replace with your own.
webhook_secret = "<WEBHOOK SECRET>"  # Optional, may be commented out.

[gitlab]
# Gitlab personal access token
personal_access_token = ""
shared_secret = ""  # webhook secret

[bitbucket]
# For Bitbucket personal/repository bearer token
bearer_token = ""

[bitbucket_server]
# For Bitbucket Server bearer token
bearer_token = ""
webhook_secret = ""

# For Bitbucket app
app_key = ""
base_url = ""

[litellm]
LITELLM_TOKEN = "" # see https://docs.litellm.ai/docs/debugging/hosted_debugging for details and instructions on how to get a token

[azure_devops]
# For Azure devops personal access token
org = ""
pat = ""

[azure_devops_server]
# For Azure devops Server basic auth - configured in the webhook creation
# Optional, uncomment if you want to use Azure devops webhooks. Value assinged when you create the webhook
# webhook_username = "<basic auth user>"
# webhook_password = "<basic auth password>"
